version: '3.9'

services:
  web:
    image: blognificent:2.0
    container_name: blognificent

    # Build context and Dockerfile path
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        maintainer: "Senzo Maseko <senzo.e.maseko@gmail.com>"
        org.opencontainers.image.title: "Blognificent"
        org.opencontainers.image.version: "2.0"
        org.opencontainers.image.description: "Django-based blog app container"
        org.opencontainers.image.source: "https://github.com/SenzoEarl/blognificent"
        org.opencontainers.image.licenses: "MIT"

    command: gunicorn blognificent.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    # No need to expose port 8000 to the host, only to the nginx container
    expose:
      - "8000"
    env_file:
      - .env
    networks:
      - blognificent_network

  nginx:
    image: nginx:alpine
    container_name: blognificent_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web
    networks:
      - blognificent_network

networks:
  blognificent_network:
    driver: bridge