[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid

[program:gunicorn]
command=gunicorn blognificent.wsgi:application --bind 0.0.0.0:8000
directory=/app
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/gunicorn/access.log
stderr_logfile=/var/log/gunicorn/error.log
environment=PYTHONUNBUFFERED=1
priority=10

[program:nginx]
command=nginx -g "daemon off;" -c /etc/nginx/nginx.combined.conf
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log
priority=20

[program:nginx-dev]
command=nginx -g "daemon off;" -c /etc/nginx/nginx.dev.combined.conf
user=root
autostart=false
autorestart=true
stdout_logfile=/var/log/nginx/access.log
stderr_logfile=/var/log/nginx/error.log
priority=20

[group:blognificent]
programs=gunicorn,nginx
priority=999